version: "3.9"

services:
  main_app:
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  rabbitmq:
    restart: always
    image: rabbitmq:3.8-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
      - 25672:25672
    environment:
      RABBITMQ_DEFAULT_VHOST: vhost
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
 
  celery_worker:
    build:
      context: .
    command: celery -A celeryconfig worker --loglevel=info
    depends_on:
      - rabbitmq
      - main_app

    stdin_open: true